### ISSUE TITLE
Seems not working with org-ref version 3

### ISSUE THREAD

**Issue by deb75** [alezost/org-ref-prettify.el#1]
Hello,

It seems references are no more prettified since `org-ref` latest released version (3).

I guess it is because the new `org-ref` adds one `&` character within the reference link.

Removing this character from the link makes `org-prettify` work again.

Regards

**Comment by alezost** [comment]
Ouch, it looks like Org-ref 3.0 introduced huge changes in the citation links.
Thank you for this report! And sorry for the long delay :)

I have added support for `&key` things with commit 0cecd7b2611bd9d282876ab46d490ce3e635ba86.

However, there is no full support for Org-ref 3.0: such links as
``[[citet:See &key line 8]]`` are not supported.

**Comment by alezost** [comment]
In case you are still interested, I have added a full support for
Org-ref 3.0 links.  Hopefully, they will work properly now :-)
