### ISSUE TITLE
citep not recognized

### ISSUE THREAD

**Issue by baracunatana** [alezost/org-ref-prettify.el#5]
Hi

Thanks a lot for this excelent package. It is a great addition to academics using emacs.

I usually use `citep` (instead of `parencite`), and it turns out that `citep` is not recognize by `org-ref-prettify` as a citation command and isn't prettified in any way. After a bit or online browsing, I now realize that I should be using `parencite`. However, for compatibility purposes, is it possible to add `citep`?

Thanks,

**Comment by alezost** [comment]
Hello and sorry for the delay.

`citep` is prettified for me.  Well, I mean it does not work the same as
`parencite` but the prettification works.  If I understand correctly,
`citep` is not prettified for you at all, right?

If so, could you check `org-ref-cite-types` variable (with `C-h v` for example)?
If it contains `citep`, then prettification should work for it.

Or did you mean that `citep` should look the same as `parencite`?

**Comment by baracunatana** [comment]
Hi

No worries for the delay. 

I just did a general update on my pc and it now works as you describe. However, given that `citep` is an alias for `parencite`, they should look the same.

**Comment by alezost** [comment]
OK, it should be fixed with commit cbf9a70. Thank you for the report!
Let me know if something is not work as expected still.

**Comment by baracunatana** [comment]
Works as intended. Thanks.
